routes/web.php
<?php

Route::redirect('/', '/login');
Route::redirect('/home', '/admin');
Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    
    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Pacientes
    Route::delete('pacientes/destroy', 'PacienteController@massDestroy')->name('pacientes.massDestroy');
    Route::post('pacientes/media', 'PacienteController@storeMedia')->name('pacientes.storeMedia');
    Route::resource('pacientes', 'PacienteController');

    // Services
    Route::delete('services/destroy', 'ServiceController@massDestroy')->name('services.massDestroy');
    Route::resource('services', 'ServiceController');

    // Atendimentos
    Route::delete('atendimentos/destroy', 'AtendimentoController@massDestroy')->name('atendimentos.massDestroy');
    Route::post('atendimentos/media', 'AtendimentoController@storeMedia')->name('atendimentos.storeMedia');
    Route::resource('atendimentos', 'AtendimentoController');

    //Perfil

  
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/terapeutaHome/index.blade.php
@extends('layouts.admin')
@section('content')
@can('paciente_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.pacientes.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.paciente.title_singular') }}
            </a>
        </div>
    </div>
@endcan


<div class="card">
    <div class="card-header">
        {{ trans('cruds.paciente.title_singular') }} {{ trans('global.list') }}
    </div>


    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Paciente">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.nome') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.dni') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.codigo') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.nascimento') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.area') }}
                        </th>
 
                        <th>
                            {{ trans('cruds.paciente.fields.sexo') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.email') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.direccion') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.alergia') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.sanguineo') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.civil') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.telefono') }}
                        </th>
                        <th>
                            {{ trans('cruds.paciente.fields.observacoes') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($pacientes as $key => $paciente)
                        <tr data-entry-id="{{ $paciente->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $paciente->id ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->nome ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->dni ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->codigo ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->nascimento ?? '' }}
                            </td>
                            <td>
                                {{ App\Paciente::AREA_SELECT[$paciente->area] ?? '' }}
                            </td>

                            <td>
                                {{ App\Paciente::SEXO_RADIO[$paciente->sexo] ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->email ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->direccion ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->alergia ?? '' }}
                            </td>
                            <td>
                                {{ App\Paciente::G_Sanguineo[$paciente->sanguineo] ?? '' }}
                            </td>

                            <td>
                                {{ App\Paciente::E_Civil[$paciente->civil] ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->telefono ?? '' }}
                            </td>
                            <td>
                                {{ $paciente->observacoes ?? '' }}
                            </td>
                            <td>
                                @can('paciente_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.pacientes.show', $paciente->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('paciente_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.pacientes.edit', $paciente->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('paciente_delete')
                                    <form action="{{ route('admin.pacientes.destroy', $paciente->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('paciente_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.pacientes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Paciente:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection